apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-web-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-web-app
      app.kubernetes.io/component: web-app
