spring:
  datasource:
    url: ${TODO_DB_URL:${DB_URL:jdbc:postgresql://${TODO_DB_HOST}:${TODO_DB_PORT}/${TODO_DB_NAME}}}
    username: ${TODO_DB_USERNAME:${DB_USERNAME}}
    password: ${TODO_DB_PASSWORD:${DB_PASSWORD}}

management:
  endpoints:
    web:
      exposure:
        include: ${TODO_OBS_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus}

  endpoint:
    health:
      show-components: ${TODO_OBS_HEALTH_SHOW_COMPONENTS:never}
      show-details: ${TODO_OBS_HEALTH_SHOW_DETAILS:${ACTUATOR_HEALTH_SHOW_DETAILS:never}}
