server:
  port: ${TODO_APP_SERVER_PORT:${SERVER_PORT:8080}}
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: ${TODO_APP_NAME:${APP_NAME:todo-web-app}}
  datasource:
    url: ${TODO_DB_URL:${DB_URL:jdbc:postgresql://${TODO_DB_HOST:localhost}:${TODO_DB_PORT:5432}/${TODO_DB_NAME:todo}}}
    username: ${TODO_DB_USERNAME:${DB_USERNAME:postgres}}
    password: ${TODO_DB_PASSWORD:${DB_PASSWORD:postgres}}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${TODO_KAFKA_BOOTSTRAP_SERVERS:${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}}

todo:
  kafka:
    enabled: ${TODO_KAFKA_ENABLED:false}
    bootstrap-servers: ${TODO_KAFKA_BOOTSTRAP_SERVERS:${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}}
    consumer-group-id: ${TODO_KAFKA_CONSUMER_GROUP_ID:todo-web-app-reminder-scheduled-v1}
    topics:
      reminder-scheduled-v1: ${TODO_KAFKA_TOPIC_REMINDER_SCHEDULED_V1:todo.reminder.scheduled.v1}

management:
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      slo:
        "[http.server.requests]": 100ms,250ms,500ms,1s,2s,5s

  prometheus:
    metrics:
      export:
        enabled: true
